### ISSUE TITLE
Audio mutes when increasing speed

### ISSUE THREAD

**Issue by JaiGupta13** [ritamsarmah/accelerate#8]
### Description

When increasing playback speed on youtube, the audio mutes for a few seconds and then plays again. Happens all the time.

### Steps to Reproduce

Open youtube and adjust playback speed.

### Expected Behavior

Video speed increases without muting.

### Accelerate Version

4.2.0

### Operating System

macOS

### Additional Info

13in M2 MacBook air. MacOS 14.3.1. Safari 14.3.1 19617.2.4.11.12.

**Comment by ritamsarmah** [comment]
Hi @JaiGupta13,

Thanks for reporting the issue. From my understanding, this would be a problem from Safari's video playback behavior and is addressed in Accelerate's [FAQ](https://ritam.me/projects/accelerate/faq/):

> **Why does the video briefly lag after changing speed or skipping?**
>
> By default, videos in Safari pause for a split second anytime the user adjusts playback, like when changing speed or skipping. You can observe this behavior on videos even without Accelerate when using a website's integrated video controls. Since this is a result of Safari's video processing, this issue currently cannot be fixed by Accelerate.

You can try comparing the behavior on YouTube when using their built-in playback speed shortcuts (`Shift + ,` and `Shift + .`) to confirm if this issue is specific to Accelerate. I've personally observed the same behavior with and without using Accelerate to control video playback.
